---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: integration-resolver-pipelinerun-
spec:
  pipelineRef:
    resolver: git
    params:
    - name: url 
      value: http://github.com/konflux-ci/integration-examples.git 
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/integration_resolver_pipeline_pass.yaml
